// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    persons,
    families,
    familyPartners,
    familyChildren,
    events,
    cemeteries,
    graves,
    burials,
    assertions,
    media,
    settings,
  ];
  late final Shape0 persons = Shape0(
    source: i0.VersionedTable(
      entityName: 'persons',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 families = Shape1(
    source: i0.VersionedTable(
      entityName: 'families',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 familyPartners = Shape2(
    source: i0.VersionedTable(
      entityName: 'family_partners',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(family_id, person_id)'],
      columns: [_column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 familyChildren = Shape2(
    source: i0.VersionedTable(
      entityName: 'family_children',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(family_id, person_id)'],
      columns: [_column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 events = Shape3(
    source: i0.VersionedTable(
      entityName: 'events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((person_id IS NULL)<>(family_id IS NULL))',
        'CHECK((type IN (\'birth\', \'death\', \'burial\'))=(person_id IS NOT NULL))',
      ],
      columns: [
        _column_0,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 cemeteries = Shape4(
    source: i0.VersionedTable(
      entityName: 'cemeteries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 graves = Shape5(
    source: i0.VersionedTable(
      entityName: 'graves',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 burials = Shape6(
    source: i0.VersionedTable(
      entityName: 'burials',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(person_id, grave_id)'],
      columns: [_column_0, _column_8, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 assertions = Shape7(
    source: i0.VersionedTable(
      entityName: 'assertions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['CHECK((event_id IS NULL)<>(burial_id IS NULL))'],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 media = Shape8(
    source: i0.VersionedTable(
      entityName: 'media',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['CHECK((person_id IS NULL)<>(grave_id IS NULL))'],
      columns: [_column_0, _column_40, _column_10, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 settings = Shape9(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [_column_42, _column_43],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get givenNames =>
      columnsByName['given_names']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get surname =>
      columnsByName['surname']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get birthSurname =>
      columnsByName['birth_surname']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bio =>
      columnsByName['bio']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bioSource =>
      columnsByName['bio_source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isLiving =>
      columnsByName['is_living']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'given_names',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'surname',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_3(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'birth_surname',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'bio',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'bio_source',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_living',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_living IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
}

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get familyId =>
      columnsByName['family_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get personId =>
      columnsByName['person_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_7(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'family_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES families(id)',
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'person_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES persons(id)',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get type =>
      columnsByName['type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get personId =>
      columnsByName['person_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get familyId =>
      columnsByName['family_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get qualifier =>
      columnsByName['qualifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get year =>
      columnsByName['year']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get month =>
      columnsByName['month']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get day =>
      columnsByName['day']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get yearTo =>
      columnsByName['year_to']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get monthTo =>
      columnsByName['month_to']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dayTo =>
      columnsByName['day_to']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get place =>
      columnsByName['place']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'person_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES persons(id)',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'family_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES families(id)',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'qualifier',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'year',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'month',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'day',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'year_to',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'month_to',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'day_to',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'place',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get locality =>
      columnsByName['locality']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get centerLat =>
      columnsByName['center_lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get centerLon =>
      columnsByName['center_lon']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get grobonetUrl =>
      columnsByName['grobonet_url']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'locality',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_22(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'center_lat',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_23(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'center_lon',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'grobonet_url',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cemeteryId =>
      columnsByName['cemetery_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sector =>
      columnsByName['sector']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get row =>
      columnsByName['row']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get plot =>
      columnsByName['plot']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get lat =>
      columnsByName['lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lon =>
      columnsByName['lon']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get positionSource =>
      columnsByName['position_source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get positionAccuracyM =>
      columnsByName['position_accuracy_m']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cemetery_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES cemeteries(id)',
    );
i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sector',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'row',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'plot',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_29(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'lat',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_30(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'lon',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'position_source',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_32(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'position_accuracy_m',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get personId =>
      columnsByName['person_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get graveId =>
      columnsByName['grave_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'grave_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES graves(id)',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get eventId =>
      columnsByName['event_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get burialId =>
      columnsByName['burial_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sourceKind =>
      columnsByName['source_kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceDetail =>
      columnsByName['source_detail']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get recordedAt =>
      columnsByName['recorded_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'event_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES events(id)',
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'burial_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES burials(id)',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_detail',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'status',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'recorded_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get relativePath =>
      columnsByName['relative_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get personId =>
      columnsByName['person_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get graveId =>
      columnsByName['grave_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'relative_path',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'grave_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES graves(id)',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get mePersonId =>
      columnsByName['me_person_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'me_person_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES persons(id)',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    persons,
    families,
    familyPartners,
    familyChildren,
    events,
    cemeteries,
    graves,
    burials,
    assertions,
    media,
    settings,
  ];
  late final Shape0 persons = Shape0(
    source: i0.VersionedTable(
      entityName: 'persons',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 families = Shape1(
    source: i0.VersionedTable(
      entityName: 'families',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 familyPartners = Shape2(
    source: i0.VersionedTable(
      entityName: 'family_partners',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(family_id, person_id)'],
      columns: [_column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 familyChildren = Shape2(
    source: i0.VersionedTable(
      entityName: 'family_children',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(family_id, person_id)'],
      columns: [_column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 events = Shape3(
    source: i0.VersionedTable(
      entityName: 'events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((person_id IS NULL)<>(family_id IS NULL))',
        'CHECK((type IN (\'birth\', \'death\', \'burial\'))=(person_id IS NOT NULL))',
      ],
      columns: [
        _column_0,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 cemeteries = Shape4(
    source: i0.VersionedTable(
      entityName: 'cemeteries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 graves = Shape10(
    source: i0.VersionedTable(
      entityName: 'graves',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_25,
        _column_44,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 burials = Shape6(
    source: i0.VersionedTable(
      entityName: 'burials',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(person_id, grave_id)'],
      columns: [_column_0, _column_8, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 assertions = Shape7(
    source: i0.VersionedTable(
      entityName: 'assertions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['CHECK((event_id IS NULL)<>(burial_id IS NULL))'],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 media = Shape8(
    source: i0.VersionedTable(
      entityName: 'media',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['CHECK((person_id IS NULL)<>(grave_id IS NULL))'],
      columns: [_column_0, _column_40, _column_10, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 settings = Shape9(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [_column_42, _column_43],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cemeteryId =>
      columnsByName['cemetery_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sector =>
      columnsByName['sector']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get row =>
      columnsByName['row']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get plot =>
      columnsByName['plot']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get lat =>
      columnsByName['lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lon =>
      columnsByName['lon']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get positionSource =>
      columnsByName['position_source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get positionAccuracyM =>
      columnsByName['position_accuracy_m']! as i1.GeneratedColumn<double>;
}

i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    persons,
    families,
    familyPartners,
    familyChildren,
    events,
    cemeteries,
    graves,
    burials,
    assertions,
    media,
    personMedia,
    settings,
    personMediaMedia,
  ];
  late final Shape0 persons = Shape0(
    source: i0.VersionedTable(
      entityName: 'persons',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 families = Shape1(
    source: i0.VersionedTable(
      entityName: 'families',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 familyPartners = Shape2(
    source: i0.VersionedTable(
      entityName: 'family_partners',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(family_id, person_id)'],
      columns: [_column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 familyChildren = Shape2(
    source: i0.VersionedTable(
      entityName: 'family_children',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(family_id, person_id)'],
      columns: [_column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 events = Shape3(
    source: i0.VersionedTable(
      entityName: 'events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((person_id IS NULL)<>(family_id IS NULL))',
        'CHECK((type IN (\'birth\', \'death\', \'burial\'))=(person_id IS NOT NULL))',
      ],
      columns: [
        _column_0,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 cemeteries = Shape4(
    source: i0.VersionedTable(
      entityName: 'cemeteries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 graves = Shape10(
    source: i0.VersionedTable(
      entityName: 'graves',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_25,
        _column_44,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 burials = Shape6(
    source: i0.VersionedTable(
      entityName: 'burials',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(person_id, grave_id)'],
      columns: [_column_0, _column_8, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 assertions = Shape7(
    source: i0.VersionedTable(
      entityName: 'assertions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['CHECK((event_id IS NULL)<>(burial_id IS NULL))'],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 media = Shape11(
    source: i0.VersionedTable(
      entityName: 'media',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_40, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 personMedia = Shape12(
    source: i0.VersionedTable(
      entityName: 'person_media',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(person_id, media_id)'],
      columns: [_column_8, _column_45, _column_46],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 settings = Shape9(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [_column_42, _column_43],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index personMediaMedia = i1.Index(
    'person_media_media',
    'CREATE INDEX person_media_media ON person_media (media_id)',
  );
}

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get relativePath =>
      columnsByName['relative_path']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get graveId =>
      columnsByName['grave_id']! as i1.GeneratedColumn<int>;
}

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get personId =>
      columnsByName['person_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get mediaId =>
      columnsByName['media_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'media_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES media(id)',
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    persons,
    families,
    familyPartners,
    familyChildren,
    events,
    cemeteries,
    graves,
    burials,
    assertions,
    media,
    personMedia,
    settings,
    personMediaMedia,
  ];
  late final Shape0 persons = Shape0(
    source: i0.VersionedTable(
      entityName: 'persons',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 families = Shape1(
    source: i0.VersionedTable(
      entityName: 'families',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 familyPartners = Shape2(
    source: i0.VersionedTable(
      entityName: 'family_partners',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(family_id, person_id)'],
      columns: [_column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 familyChildren = Shape2(
    source: i0.VersionedTable(
      entityName: 'family_children',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(family_id, person_id)'],
      columns: [_column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 events = Shape3(
    source: i0.VersionedTable(
      entityName: 'events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((person_id IS NULL)<>(family_id IS NULL))',
        'CHECK((type IN (\'birth\', \'death\', \'burial\'))=(person_id IS NOT NULL))',
      ],
      columns: [
        _column_0,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 cemeteries = Shape4(
    source: i0.VersionedTable(
      entityName: 'cemeteries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 graves = Shape10(
    source: i0.VersionedTable(
      entityName: 'graves',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_25,
        _column_44,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 burials = Shape6(
    source: i0.VersionedTable(
      entityName: 'burials',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(person_id, grave_id)'],
      columns: [_column_0, _column_8, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 assertions = Shape7(
    source: i0.VersionedTable(
      entityName: 'assertions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['CHECK((event_id IS NULL)<>(burial_id IS NULL))'],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 media = Shape11(
    source: i0.VersionedTable(
      entityName: 'media',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_40, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 personMedia = Shape13(
    source: i0.VersionedTable(
      entityName: 'person_media',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(person_id, media_id)'],
      columns: [
        _column_8,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 settings = Shape9(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [_column_42, _column_43],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index personMediaMedia = i1.Index(
    'person_media_media',
    'CREATE INDEX person_media_media ON person_media (media_id)',
  );
}

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get personId =>
      columnsByName['person_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get mediaId =>
      columnsByName['media_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cropLeft =>
      columnsByName['crop_left']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cropTop =>
      columnsByName['crop_top']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cropWidth =>
      columnsByName['crop_width']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cropHeight =>
      columnsByName['crop_height']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'crop_left',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'crop_top',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'crop_width',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'crop_height',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    persons,
    families,
    familyPartners,
    familyChildren,
    events,
    cemeteries,
    graves,
    burials,
    assertions,
    media,
    personMedia,
    settings,
    personMediaMedia,
  ];
  late final Shape0 persons = Shape0(
    source: i0.VersionedTable(
      entityName: 'persons',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 families = Shape1(
    source: i0.VersionedTable(
      entityName: 'families',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 familyPartners = Shape2(
    source: i0.VersionedTable(
      entityName: 'family_partners',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(family_id, person_id)'],
      columns: [_column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 familyChildren = Shape14(
    source: i0.VersionedTable(
      entityName: 'family_children',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(family_id, person_id)'],
      columns: [_column_0, _column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 events = Shape3(
    source: i0.VersionedTable(
      entityName: 'events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((person_id IS NULL)<>(family_id IS NULL))',
        'CHECK((type IN (\'birth\', \'death\', \'burial\'))=(person_id IS NOT NULL))',
      ],
      columns: [
        _column_0,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 cemeteries = Shape4(
    source: i0.VersionedTable(
      entityName: 'cemeteries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 graves = Shape10(
    source: i0.VersionedTable(
      entityName: 'graves',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_25,
        _column_44,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 burials = Shape6(
    source: i0.VersionedTable(
      entityName: 'burials',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(person_id, grave_id)'],
      columns: [_column_0, _column_8, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 assertions = Shape15(
    source: i0.VersionedTable(
      entityName: 'assertions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((event_id IS NOT NULL)+(burial_id IS NOT NULL)+(family_id IS NOT NULL)+(family_child_id IS NOT NULL)= 1)',
      ],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_11,
        _column_51,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 media = Shape11(
    source: i0.VersionedTable(
      entityName: 'media',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_40, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 personMedia = Shape13(
    source: i0.VersionedTable(
      entityName: 'person_media',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(person_id, media_id)'],
      columns: [
        _column_8,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 settings = Shape9(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [_column_42, _column_43],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index personMediaMedia = i1.Index(
    'person_media_media',
    'CREATE INDEX person_media_media ON person_media (media_id)',
  );
}

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get familyId =>
      columnsByName['family_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get personId =>
      columnsByName['person_id']! as i1.GeneratedColumn<int>;
}

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get eventId =>
      columnsByName['event_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get burialId =>
      columnsByName['burial_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get familyId =>
      columnsByName['family_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get familyChildId =>
      columnsByName['family_child_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sourceKind =>
      columnsByName['source_kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceDetail =>
      columnsByName['source_detail']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get status =>
      columnsByName['status']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get recordedAt =>
      columnsByName['recorded_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_51(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'family_child_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES family_children(id)',
    );

final class Schema7 extends i0.VersionedSchema {
  Schema7({required super.database}) : super(version: 7);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    persons,
    families,
    familyPartners,
    familyChildren,
    events,
    cemeteries,
    graves,
    burials,
    assertions,
    media,
    personMedia,
    settings,
    personMediaMedia,
  ];
  late final Shape16 persons = Shape16(
    source: i0.VersionedTable(
      entityName: 'persons',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_52,
        _column_4,
        _column_5,
        _column_6,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 families = Shape1(
    source: i0.VersionedTable(
      entityName: 'families',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 familyPartners = Shape2(
    source: i0.VersionedTable(
      entityName: 'family_partners',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(family_id, person_id)'],
      columns: [_column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 familyChildren = Shape14(
    source: i0.VersionedTable(
      entityName: 'family_children',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(family_id, person_id)'],
      columns: [_column_0, _column_7, _column_8],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 events = Shape3(
    source: i0.VersionedTable(
      entityName: 'events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((person_id IS NULL)<>(family_id IS NULL))',
        'CHECK((type IN (\'birth\', \'death\', \'burial\'))=(person_id IS NOT NULL))',
      ],
      columns: [
        _column_0,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 cemeteries = Shape4(
    source: i0.VersionedTable(
      entityName: 'cemeteries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 graves = Shape10(
    source: i0.VersionedTable(
      entityName: 'graves',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_25,
        _column_44,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 burials = Shape6(
    source: i0.VersionedTable(
      entityName: 'burials',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['UNIQUE(person_id, grave_id)'],
      columns: [_column_0, _column_8, _column_33],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 assertions = Shape15(
    source: i0.VersionedTable(
      entityName: 'assertions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK((event_id IS NOT NULL)+(burial_id IS NOT NULL)+(family_id IS NOT NULL)+(family_child_id IS NOT NULL)= 1)',
      ],
      columns: [
        _column_0,
        _column_34,
        _column_35,
        _column_11,
        _column_51,
        _column_36,
        _column_37,
        _column_38,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 media = Shape11(
    source: i0.VersionedTable(
      entityName: 'media',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_40, _column_41],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 personMedia = Shape13(
    source: i0.VersionedTable(
      entityName: 'person_media',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(person_id, media_id)'],
      columns: [
        _column_8,
        _column_45,
        _column_46,
        _column_47,
        _column_48,
        _column_49,
        _column_50,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 settings = Shape9(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'CHECK(id = 1)'],
      columns: [_column_42, _column_43],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index personMediaMedia = i1.Index(
    'person_media_media',
    'CREATE INDEX person_media_media ON person_media (media_id)',
  );
}

class Shape16 extends i0.VersionedTable {
  Shape16({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get givenNames =>
      columnsByName['given_names']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get surname =>
      columnsByName['surname']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get birthSurname =>
      columnsByName['birth_surname']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sex =>
      columnsByName['sex']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bio =>
      columnsByName['bio']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bioSource =>
      columnsByName['bio_source']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isLiving =>
      columnsByName['is_living']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sex',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      case 6:
        final schema = Schema7(database: database);
        final migrator = i1.Migrator(database, schema);
        await from6To7(migrator, schema);
        return 7;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
    from6To7: from6To7,
  ),
);
