import 'dart:convert';
import 'dart:typed_data';

// The ustar archive inside a backup: regular files only, so `tar` on any PC reads it (ADR-004 pkt 2).
// Format: POSIX `pax` → ustar Interchange Format
// (https://pubs.opengroup.org/onlinepubs/9699919799/utilities/pax.html#tag_20_92_13_06).

const int tarBlockSize = 512;

/// The largest file a ustar header can describe: 11 octal digits.
const int tarMaxFileSize = 0x1ffffffff; // 8 GiB - 1

/// Paths are generated by the app: ASCII letters, digits, `.`, `_` and `-` in `/`-separated
/// segments, never `.` or `..`. Anything else is refused rather than renamed silently.
final RegExp _safePath = RegExp(r'^[A-Za-z0-9._-]+(/[A-Za-z0-9._-]+)*$');

class TarPathException implements Exception {
  const TarPathException(this.message);

  final String message;

  @override
  String toString() => 'TarPathException: $message';
}

/// The 512-byte ustar header of one regular file.
Uint8List tarFileHeader(String path, int size, DateTime modified) {
  if (!_safePath.hasMatch(path) ||
      path.split('/').any((s) => s == '.' || s == '..')) {
    throw const TarPathException('Path outside the safe ASCII set');
  }
  if (size < 0 || size > tarMaxFileSize) {
    throw const TarPathException('File too large for ustar');
  }
  final (String prefix, String name) = _split(path);

  final Uint8List header = Uint8List(tarBlockSize);
  _text(header, 0, 100, name);
  _octal(header, 100, 8, 0x1a4); // mode 0644
  _octal(header, 108, 8, 0); // uid
  _octal(header, 116, 8, 0); // gid
  _octal(header, 124, 12, size);
  _octal(header, 136, 12, modified.millisecondsSinceEpoch ~/ 1000);
  header.fillRange(
    148,
    156,
    0x20,
  ); // checksum counts as spaces while it is computed
  header[156] = 0x30; // '0': regular file
  _text(header, 257, 6, 'ustar'); // magic, NUL-terminated
  _text(header, 263, 2, '00'); // version
  _octal(header, 329, 8, 0); // devmajor
  _octal(header, 337, 8, 0); // devminor
  _text(header, 345, 155, prefix);

  final int checksum = header.fold(0, (sum, b) => sum + b);
  _text(header, 148, 6, checksum.toRadixString(8).padLeft(6, '0'));
  header[154] = 0;
  header[155] = 0x20;
  return header;
}

/// Zero bytes that pad a file of [size] bytes to a whole block.
Uint8List tarPadding(int size) =>
    Uint8List((tarBlockSize - size % tarBlockSize) % tarBlockSize);

/// The end of an archive: two zero blocks.
Uint8List tarEnd() => Uint8List(2 * tarBlockSize);

/// name ≤ 100, prefix ≤ 155, split at a `/`.
(String, String) _split(String path) {
  if (path.length <= 100) return ('', path);
  for (int i = path.indexOf('/'); i >= 0; i = path.indexOf('/', i + 1)) {
    if (i <= 155 && path.length - i - 1 <= 100) {
      return (path.substring(0, i), path.substring(i + 1));
    }
  }
  throw const TarPathException('Path too long for ustar');
}

void _text(Uint8List header, int offset, int length, String value) {
  final List<int> bytes = ascii.encode(value);
  header.setRange(offset, offset + bytes.length, bytes);
}

/// Zero-padded octal digits followed by NUL, filling [length] bytes.
void _octal(Uint8List header, int offset, int length, int value) {
  _text(
    header,
    offset,
    length - 1,
    value.toRadixString(8).padLeft(length - 1, '0'),
  );
  header[offset + length - 1] = 0;
}
