// dart format width=80
// ignore_for_file: unused_local_variable, unused_import
import 'package:drift/drift.dart';
import 'package:drift_dev/api/migrations_native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:grobing/data/database.dart';
import 'generated/schema.dart';

import 'generated/schema_v1.dart' as v1;
import 'generated/schema_v2.dart' as v2;

// NFR-003: every schema change ships with a migration tested from the previous version. Generated by
// `make-migrations`; the data test below is ISSUE-011 AC-3. Made-up people only (family-data.md).

void main() {
  driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
  late SchemaVerifier verifier;

  setUpAll(() {
    verifier = SchemaVerifier(GeneratedHelper());
  });

  group('simple database migrations', () {
    // These simple tests verify all possible schema updates with a simple (no
    // data) migration. This is a quick way to ensure that written database
    // migrations properly alter the schema.
    const versions = GeneratedHelper.versions;
    for (final (i, fromVersion) in versions.indexed) {
      group('from $fromVersion', () {
        for (final toVersion in versions.skip(i + 1)) {
          test('to $toVersion', () async {
            final schema = await verifier.schemaAt(fromVersion);
            final db = GrobingDatabase(schema.newConnection());
            await verifier.migrateAndValidate(db, toVersion);
            await db.close();
          });
        }
      });
    }
  });

  test(
    'ISSUE-011 AC-3 — v1 to v2 keeps every row; burials keep their order, '
    'and every date and burial gets one claim carried over from v1 (D5)',
    () async {
      const List<v1.PersonsData> persons = [
        v1.PersonsData(
          id: 1,
          givenNames: 'Ojciec 1',
          surname: 'Wymyślona',
          bio: 'Osoba wymyślona do testów.',
          bioSource: 'dane testowe',
          isLiving: 0,
        ),
        v1.PersonsData(
          id: 2,
          givenNames: 'Matka 1',
          surname: 'Wymyślona',
          birthSurname: 'Zmyślona',
          isLiving: 0,
        ),
        v1.PersonsData(id: 3, givenNames: 'Dziecko 1', isLiving: 1),
      ];
      const List<v1.CemeteriesData> cemeteries = [
        v1.CemeteriesData(id: 1, name: 'Cmentarz Wymyślony 1'),
      ];
      const List<v1.GravesData> graves = [
        v1.GravesData(id: 1, cemeteryId: 1),
        v1.GravesData(id: 2, cemeteryId: 1, sector: 'B', row: '3', plot: '12'),
      ];
      const List<v1.EventsData> events = [
        v1.EventsData(
          id: 1,
          type: 'birth',
          personId: 1,
          qualifier: 'about',
          year: 1890,
        ),
        v1.EventsData(
          id: 2,
          type: 'death',
          personId: 1,
          qualifier: 'exact',
          year: 1951,
          month: 3,
          day: 14,
        ),
        v1.EventsData(
          id: 3,
          type: 'birth',
          personId: 2,
          qualifier: 'between',
          year: 1893,
          yearTo: 1895,
        ),
      ];
      // Not in person order: the new id comes from the row (its rowid), not
      // from the person.
      const List<v1.BurialsData> burials = [
        v1.BurialsData(personId: 3, graveId: 2),
        v1.BurialsData(personId: 1, graveId: 1),
        v1.BurialsData(personId: 2, graveId: 1),
      ];
      final int before = DateTime.now().millisecondsSinceEpoch ~/ 1000;

      await verifier.testWithDataIntegrity(
        oldVersion: 1,
        newVersion: 2,
        createOld: v1.DatabaseAtV1.new,
        createNew: v2.DatabaseAtV2.new,
        openTestedDatabase: GrobingDatabase.new,
        createItems: (batch, oldDb) {
          batch.insertAll(oldDb.persons, persons);
          batch.insertAll(oldDb.cemeteries, cemeteries);
          batch.insertAll(oldDb.graves, graves);
          batch.insertAll(oldDb.events, events);
          batch.insertAll(oldDb.burials, burials);
        },
        validateItems: (newDb) async {
          // Tables v2 does not reshape: the same rows, value for value.
          void same(List<DataClass> now, List<DataClass> then) =>
              expect(now.map((r) => r.toJson()), then.map((r) => r.toJson()));
          same(await newDb.select(newDb.persons).get(), persons);
          same(await newDb.select(newDb.cemeteries).get(), cemeteries);
          same(await newDb.select(newDb.graves).get(), graves);
          same(await newDb.select(newDb.events).get(), events);

          expect(
            (await newDb.select(newDb.burials).get()).map(
              (b) => (b.id, b.personId, b.graveId),
            ),
            [(1, 3, 2), (2, 1, 1), (3, 2, 1)],
          );

          final int after = DateTime.now().millisecondsSinceEpoch ~/ 1000;
          final List<v2.AssertionsData> claims = await newDb
              .select(newDb.assertions)
              .get();
          expect(
            claims.map(
              (c) => (
                c.eventId,
                c.burialId,
                c.sourceKind,
                c.sourceDetail,
                c.status,
              ),
            ),
            [
              for (final int e in [1, 2, 3])
                (e, null, 'notes', carriedOverFromV1, 'claimed'),
              for (final int b in [1, 2, 3])
                (null, b, 'notes', carriedOverFromV1, 'claimed'),
            ],
          );
          expect(
            claims.map((c) => c.recordedAt),
            everyElement(inInclusiveRange(before, after)),
          );
        },
      );
    },
  );
}
