// dart format width=80
// ignore_for_file: unused_local_variable, unused_import
import 'package:drift/drift.dart';
import 'package:drift_dev/api/migrations_native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:grobing/data/database.dart';
import 'generated/schema.dart';

import 'generated/schema_v1.dart' as v1;
import 'generated/schema_v2.dart' as v2;
import 'generated/schema_v3.dart' as v3;
import 'generated/schema_v4.dart' as v4;
import 'generated/schema_v5.dart' as v5;
import 'generated/schema_v6.dart' as v6;
import 'generated/schema_v7.dart' as v7;

// NFR-003: every schema change ships with a migration tested from the previous version. Generated by
// `make-migrations`; the data tests below are ISSUE-011 AC-3 (v1→v2), ISSUE-012 (v2→v3), ISSUE-017
// F2 (v3→v4), ISSUE-018 F2 (v4→v5), ISSUE-019 F1 (v5→v6) and ISSUE-025 AC-4 (v6→v7). Made-up people only
// (family-data.md).

void main() {
  driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
  late SchemaVerifier verifier;

  setUpAll(() {
    verifier = SchemaVerifier(GeneratedHelper());
  });

  group('simple database migrations', () {
    // These simple tests verify all possible schema updates with a simple (no
    // data) migration. This is a quick way to ensure that written database
    // migrations properly alter the schema.
    const versions = GeneratedHelper.versions;
    for (final (i, fromVersion) in versions.indexed) {
      group('from $fromVersion', () {
        for (final toVersion in versions.skip(i + 1)) {
          test('to $toVersion', () async {
            final schema = await verifier.schemaAt(fromVersion);
            final db = GrobingDatabase(schema.newConnection());
            await verifier.migrateAndValidate(db, toVersion);
            await db.close();
          });
        }
      });
    }
  });

  test(
    'ISSUE-011 AC-3 — v1 to v2 keeps every row; burials keep their order, '
    'and every date and burial gets one claim carried over from v1 (D5)',
    () async {
      const List<v1.PersonsData> persons = [
        v1.PersonsData(
          id: 1,
          givenNames: 'Ojciec 1',
          surname: 'Wymyślona',
          bio: 'Osoba wymyślona do testów.',
          bioSource: 'dane testowe',
          isLiving: 0,
        ),
        v1.PersonsData(
          id: 2,
          givenNames: 'Matka 1',
          surname: 'Wymyślona',
          birthSurname: 'Zmyślona',
          isLiving: 0,
        ),
        v1.PersonsData(id: 3, givenNames: 'Dziecko 1', isLiving: 1),
      ];
      const List<v1.CemeteriesData> cemeteries = [
        v1.CemeteriesData(id: 1, name: 'Cmentarz Wymyślony 1'),
      ];
      const List<v1.GravesData> graves = [
        v1.GravesData(id: 1, cemeteryId: 1),
        v1.GravesData(id: 2, cemeteryId: 1, sector: 'B', row: '3', plot: '12'),
      ];
      const List<v1.EventsData> events = [
        v1.EventsData(
          id: 1,
          type: 'birth',
          personId: 1,
          qualifier: 'about',
          year: 1890,
        ),
        v1.EventsData(
          id: 2,
          type: 'death',
          personId: 1,
          qualifier: 'exact',
          year: 1951,
          month: 3,
          day: 14,
        ),
        v1.EventsData(
          id: 3,
          type: 'birth',
          personId: 2,
          qualifier: 'between',
          year: 1893,
          yearTo: 1895,
        ),
      ];
      // Not in person order: the new id comes from the row (its rowid), not
      // from the person.
      const List<v1.BurialsData> burials = [
        v1.BurialsData(personId: 3, graveId: 2),
        v1.BurialsData(personId: 1, graveId: 1),
        v1.BurialsData(personId: 2, graveId: 1),
      ];
      final int before = DateTime.now().millisecondsSinceEpoch ~/ 1000;

      await verifier.testWithDataIntegrity(
        oldVersion: 1,
        newVersion: 2,
        createOld: v1.DatabaseAtV1.new,
        createNew: v2.DatabaseAtV2.new,
        openTestedDatabase: GrobingDatabase.new,
        createItems: (batch, oldDb) {
          batch.insertAll(oldDb.persons, persons);
          batch.insertAll(oldDb.cemeteries, cemeteries);
          batch.insertAll(oldDb.graves, graves);
          batch.insertAll(oldDb.events, events);
          batch.insertAll(oldDb.burials, burials);
        },
        validateItems: (newDb) async {
          // Tables v2 does not reshape: the same rows, value for value.
          void same(List<DataClass> now, List<DataClass> then) =>
              expect(now.map((r) => r.toJson()), then.map((r) => r.toJson()));
          same(await newDb.select(newDb.persons).get(), persons);
          same(await newDb.select(newDb.cemeteries).get(), cemeteries);
          same(await newDb.select(newDb.graves).get(), graves);
          same(await newDb.select(newDb.events).get(), events);

          expect(
            (await newDb.select(newDb.burials).get()).map(
              (b) => (b.id, b.personId, b.graveId),
            ),
            [(1, 3, 2), (2, 1, 1), (3, 2, 1)],
          );

          final int after = DateTime.now().millisecondsSinceEpoch ~/ 1000;
          final List<v2.AssertionsData> claims = await newDb
              .select(newDb.assertions)
              .get();
          expect(
            claims.map(
              (c) => (
                c.eventId,
                c.burialId,
                c.sourceKind,
                c.sourceDetail,
                c.status,
              ),
            ),
            [
              for (final int e in [1, 2, 3])
                (e, null, 'notes', carriedOverFromV1, 'claimed'),
              for (final int b in [1, 2, 3])
                (null, b, 'notes', carriedOverFromV1, 'claimed'),
            ],
          );
          expect(
            claims.map((c) => c.recordedAt),
            everyElement(inInclusiveRange(before, after)),
          );
        },
      );
    },
  );

  test(
    'ISSUE-012 — v2 to v3 keeps every row value for value; graves get an empty name',
    () async {
      const List<v2.PersonsData> persons = [
        v2.PersonsData(
          id: 1,
          givenNames: 'Jan',
          surname: 'Wymyślony',
          bio: 'Kowal, wymyślony do testów.',
          bioSource: 'notatki',
          isLiving: 0,
        ),
        v2.PersonsData(
          id: 2,
          givenNames: 'Anna',
          surname: 'Wymyślona',
          birthSurname: 'Zmyślona',
          isLiving: 0,
        ),
      ];
      const List<v2.CemeteriesData> cemeteries = [
        v2.CemeteriesData(
          id: 1,
          name: 'Cmentarz Wymyślony',
          locality: 'Miejscowość Testowa',
          centerLat: 51,
          centerLon: 20,
        ),
      ];
      const List<v2.GravesData> graves = [
        v2.GravesData(id: 1, cemeteryId: 1),
        v2.GravesData(id: 2, cemeteryId: 1, sector: 'B', row: '4', plot: '12'),
      ];
      const List<v2.EventsData> events = [
        v2.EventsData(
          id: 1,
          type: 'birth',
          personId: 1,
          qualifier: 'about',
          year: 1890,
        ),
        v2.EventsData(
          id: 2,
          type: 'birth',
          personId: 2,
          qualifier: 'between',
          year: 1893,
          yearTo: 1895,
        ),
      ];
      const List<v2.BurialsData> burials = [
        v2.BurialsData(id: 1, personId: 1, graveId: 1),
        v2.BurialsData(id: 2, personId: 2, graveId: 1),
      ];
      const List<v2.AssertionsData> claims = [
        v2.AssertionsData(
          id: 1,
          eventId: 1,
          sourceKind: 'notes',
          status: 'claimed',
          recordedAt: 1791273600,
        ),
        v2.AssertionsData(
          id: 2,
          eventId: 2,
          sourceKind: 'grandmother',
          sourceDetail: 'babcia, rozmowa',
          status: 'contradicted',
          recordedAt: 1791273601,
        ),
        v2.AssertionsData(
          id: 3,
          burialId: 1,
          sourceKind: 'notes',
          status: 'claimed',
          recordedAt: 1791273602,
        ),
        v2.AssertionsData(
          id: 4,
          burialId: 2,
          sourceKind: 'notes',
          status: 'claimed',
          recordedAt: 1791273603,
        ),
      ];

      await verifier.testWithDataIntegrity(
        oldVersion: 2,
        newVersion: 3,
        createOld: v2.DatabaseAtV2.new,
        createNew: v3.DatabaseAtV3.new,
        openTestedDatabase: GrobingDatabase.new,
        createItems: (batch, oldDb) {
          batch.insertAll(oldDb.persons, persons);
          batch.insertAll(oldDb.cemeteries, cemeteries);
          batch.insertAll(oldDb.graves, graves);
          batch.insertAll(oldDb.events, events);
          batch.insertAll(oldDb.burials, burials);
          batch.insertAll(oldDb.assertions, claims);
        },
        validateItems: (newDb) async {
          void same(List<DataClass> now, List<DataClass> then) =>
              expect(now.map((r) => r.toJson()), then.map((r) => r.toJson()));
          same(await newDb.select(newDb.persons).get(), persons);
          same(await newDb.select(newDb.cemeteries).get(), cemeteries);
          same(await newDb.select(newDb.events).get(), events);
          same(await newDb.select(newDb.burials).get(), burials);
          same(await newDb.select(newDb.assertions).get(), claims);

          // Graves: the same values, and the new name empty — never derived from the people.
          final List<v3.GravesData> migrated = await newDb
              .select(newDb.graves)
              .get();
          expect(migrated.map((g) => g.name), everyElement(equals(null)));
          expect(
            migrated.map((g) => g.toJson()..remove('name')),
            graves.map((g) => g.toJson()),
          );
        },
      );
    },
  );

  test(
    'ISSUE-017 F2 — v3 to v4 keeps every row; each person photo becomes a link of that person in the order '
    'of its id (the first stays the profile), the grave keeps its photo, no reference breaks',
    () async {
      const List<v3.PersonsData> persons = [
        v3.PersonsData(
          id: 1,
          givenNames: 'Jan',
          surname: 'Wymyślony',
          isLiving: 0,
        ),
        v3.PersonsData(
          id: 2,
          givenNames: 'Anna',
          surname: 'Wymyślona',
          isLiving: 0,
        ),
        v3.PersonsData(
          id: 3,
          givenNames: 'Józef',
          surname: 'Wymyślony',
          isLiving: 0,
        ),
      ];
      const List<v3.CemeteriesData> cemeteries = [
        v3.CemeteriesData(id: 1, name: 'Cmentarz Wymyślony'),
      ];
      const List<v3.GravesData> graves = [
        v3.GravesData(id: 1, cemeteryId: 1, name: 'Grób Wymyślonych'),
      ];
      // Interleaved ids: Anna's photos are 2 and 5, so her order comes from the id, not the insert batch.
      const List<v3.MediaData> media = [
        v3.MediaData(id: 1, relativePath: 'groby/1/nagrobek.jpg', graveId: 1),
        v3.MediaData(id: 2, relativePath: 'osoby/anna-a.jpg', personId: 2),
        v3.MediaData(id: 3, relativePath: 'osoby/jan-a.jpg', personId: 1),
        v3.MediaData(id: 5, relativePath: 'osoby/anna-b.jpg', personId: 2),
      ];

      await verifier.testWithDataIntegrity(
        oldVersion: 3,
        newVersion: 4,
        createOld: v3.DatabaseAtV3.new,
        createNew: v4.DatabaseAtV4.new,
        openTestedDatabase: GrobingDatabase.new,
        createItems: (batch, oldDb) {
          batch.insertAll(oldDb.persons, persons);
          batch.insertAll(oldDb.cemeteries, cemeteries);
          batch.insertAll(oldDb.graves, graves);
          batch.insertAll(oldDb.media, media);
        },
        validateItems: (newDb) async {
          expect(
            (await newDb.select(newDb.persons).get()).map((p) => p.toJson()),
            persons.map((p) => p.toJson()),
          );
          // Every media row and id stays (a v3 restore counts them), without person_id now.
          expect(
            (await newDb.select(newDb.media).get()).map(
              (m) => (m.id, m.relativePath, m.graveId),
            ),
            media.map((m) => (m.id, m.relativePath, m.graveId)),
          );
          final List<v4.PersonMediaData> links =
              await (newDb.select(newDb.personMedia)..orderBy([
                    (l) => OrderingTerm.asc(l.personId),
                    (l) => OrderingTerm.asc(l.position),
                  ]))
                  .get();
          expect(links.map((l) => (l.personId, l.mediaId, l.position)), [
            (1, 3, 0),
            (2, 2, 0),
            (2, 5, 1),
          ]);
          // Józef had no photo and has no link; the grave's photo has none either.
          expect(
            links.where((l) => l.personId == 3 || l.mediaId == 1),
            isEmpty,
          );
          expect(
            await newDb.customSelect('PRAGMA foreign_key_check').get(),
            isEmpty,
          );
        },
      );
    },
  );

  test(
    'ISSUE-018 F2 — v4 to v5 keeps every row, link and position; every link has no crop, so every profile '
    'circle shows the middle as before; no reference breaks',
    () async {
      const List<v4.PersonsData> persons = [
        v4.PersonsData(
          id: 1,
          givenNames: 'Jan',
          surname: 'Wymyślony',
          isLiving: 0,
        ),
        v4.PersonsData(
          id: 2,
          givenNames: 'Anna',
          surname: 'Wymyślona',
          isLiving: 0,
        ),
      ];
      const List<v4.CemeteriesData> cemeteries = [
        v4.CemeteriesData(id: 1, name: 'Cmentarz Wymyślony'),
      ];
      const List<v4.GravesData> graves = [
        v4.GravesData(id: 1, cemeteryId: 1, name: 'Grób Wymyślonych'),
      ];
      // A gravestone, a photo shared by both (Jan's profile, Anna's second) and Anna's own profile.
      const List<v4.MediaData> media = [
        v4.MediaData(id: 1, relativePath: 'groby/1/nagrobek.jpg', graveId: 1),
        v4.MediaData(id: 2, relativePath: 'zdjecia/slub.jpg'),
        v4.MediaData(id: 3, relativePath: 'zdjecia/anna.jpg'),
      ];
      const List<v4.PersonMediaData> links = [
        v4.PersonMediaData(personId: 1, mediaId: 2, position: 0),
        v4.PersonMediaData(personId: 2, mediaId: 3, position: 0),
        v4.PersonMediaData(personId: 2, mediaId: 2, position: 1),
      ];

      await verifier.testWithDataIntegrity(
        oldVersion: 4,
        newVersion: 5,
        createOld: v4.DatabaseAtV4.new,
        createNew: v5.DatabaseAtV5.new,
        openTestedDatabase: GrobingDatabase.new,
        createItems: (batch, oldDb) {
          batch.insertAll(oldDb.persons, persons);
          batch.insertAll(oldDb.cemeteries, cemeteries);
          batch.insertAll(oldDb.graves, graves);
          batch.insertAll(oldDb.media, media);
          batch.insertAll(oldDb.personMedia, links);
        },
        validateItems: (newDb) async {
          expect(
            (await newDb.select(newDb.persons).get()).map((p) => p.toJson()),
            persons.map((p) => p.toJson()),
          );
          expect(
            (await newDb.select(newDb.media).get()).map(
              (m) => (m.id, m.relativePath, m.graveId),
            ),
            media.map((m) => (m.id, m.relativePath, m.graveId)),
          );
          final List<v5.PersonMediaData> after =
              await (newDb.select(newDb.personMedia)..orderBy([
                    (l) => OrderingTerm.asc(l.personId),
                    (l) => OrderingTerm.asc(l.position),
                  ]))
                  .get();
          expect(
            after.map(
              (l) => (
                l.personId,
                l.mediaId,
                l.position,
                l.cropLeft,
                l.cropTop,
                l.cropWidth,
                l.cropHeight,
              ),
            ),
            [
              (1, 2, 0, null, null, null, null),
              (2, 3, 0, null, null, null, null),
              (2, 2, 1, null, null, null, null),
            ],
          );
          expect(
            await newDb.customSelect('PRAGMA foreign_key_check').get(),
            isEmpty,
          );
        },
      );
    },
  );

  test(
    'ISSUE-019 F1 — v5 to v6 keeps every row and id; each child link gets its old rowid as its id, in '
    'order; every claim stays as it was, citing neither a family nor a link; no row is added (a v5 '
    'backup must restore with the same counts — D3); no reference breaks',
    () async {
      const List<v5.PersonsData> persons = [
        v5.PersonsData(
          id: 1,
          givenNames: 'Ojciec',
          surname: 'Wymyślony',
          isLiving: 0,
        ),
        v5.PersonsData(
          id: 2,
          givenNames: 'Matka',
          surname: 'Wymyślona',
          isLiving: 0,
        ),
        v5.PersonsData(
          id: 3,
          givenNames: 'Dziecko',
          surname: 'Wymyślone',
          isLiving: 0,
        ),
        v5.PersonsData(
          id: 4,
          givenNames: 'Partnerka',
          surname: 'Zmyślona',
          isLiving: 0,
        ),
        v5.PersonsData(
          id: 5,
          givenNames: 'Drugie dziecko',
          surname: 'Wymyślone',
          isLiving: 0,
        ),
      ];
      // The father in two unions — a second marriage (AC-2) — each with a child.
      const List<v5.FamiliesData> families = [
        v5.FamiliesData(id: 1),
        v5.FamiliesData(id: 2),
      ];
      const List<v5.FamilyPartnersData> partners = [
        v5.FamilyPartnersData(familyId: 1, personId: 1),
        v5.FamilyPartnersData(familyId: 1, personId: 2),
        v5.FamilyPartnersData(familyId: 2, personId: 1),
        v5.FamilyPartnersData(familyId: 2, personId: 4),
      ];
      // Written in this order, so their rowids — and so their ids in v6 — are 1 and 2.
      const List<v5.FamilyChildrenData> children = [
        v5.FamilyChildrenData(familyId: 2, personId: 5),
        v5.FamilyChildrenData(familyId: 1, personId: 3),
      ];
      const List<v5.EventsData> events = [
        v5.EventsData(
          id: 1,
          type: 'marriage',
          familyId: 1,
          qualifier: 'before',
          year: 1920,
        ),
        v5.EventsData(
          id: 2,
          type: 'birth',
          personId: 3,
          qualifier: 'exact',
          year: 1922,
        ),
      ];
      const List<v5.CemeteriesData> cemeteries = [
        v5.CemeteriesData(id: 1, name: 'Cmentarz Wymyślony'),
      ];
      const List<v5.GravesData> graves = [v5.GravesData(id: 1, cemeteryId: 1)];
      const List<v5.BurialsData> burials = [
        v5.BurialsData(id: 1, personId: 1, graveId: 1),
      ];
      const List<v5.AssertionsData> claims = [
        v5.AssertionsData(
          id: 1,
          eventId: 1,
          sourceKind: 'notes',
          status: 'claimed',
          recordedAt: 1,
        ),
        v5.AssertionsData(
          id: 2,
          eventId: 2,
          sourceKind: 'grandmother',
          status: 'confirmed',
          recordedAt: 2,
        ),
        v5.AssertionsData(
          id: 3,
          burialId: 1,
          sourceKind: 'notes',
          status: 'claimed',
          recordedAt: 3,
        ),
      ];
      const List<v5.MediaData> media = [
        v5.MediaData(id: 1, relativePath: 'zdjecia/slub.jpg'),
      ];
      const List<v5.PersonMediaData> links = [
        v5.PersonMediaData(
          personId: 1,
          mediaId: 1,
          position: 0,
          cropLeft: 10,
          cropTop: 20,
          cropWidth: 160,
          cropHeight: 160,
        ),
      ];

      await verifier.testWithDataIntegrity(
        oldVersion: 5,
        newVersion: 6,
        createOld: v5.DatabaseAtV5.new,
        createNew: v6.DatabaseAtV6.new,
        openTestedDatabase: GrobingDatabase.new,
        createItems: (batch, oldDb) {
          batch.insertAll(oldDb.persons, persons);
          batch.insertAll(oldDb.families, families);
          batch.insertAll(oldDb.familyPartners, partners);
          batch.insertAll(oldDb.familyChildren, children);
          batch.insertAll(oldDb.events, events);
          batch.insertAll(oldDb.cemeteries, cemeteries);
          batch.insertAll(oldDb.graves, graves);
          batch.insertAll(oldDb.burials, burials);
          batch.insertAll(oldDb.assertions, claims);
          batch.insertAll(oldDb.media, media);
          batch.insertAll(oldDb.personMedia, links);
        },
        validateItems: (newDb) async {
          expect(
            (await newDb.select(newDb.persons).get()).map((p) => p.toJson()),
            persons.map((p) => p.toJson()),
          );
          expect(
            (await newDb.select(newDb.familyPartners).get()).map(
              (p) => (p.familyId, p.personId),
            ),
            partners.map((p) => (p.familyId, p.personId)),
          );
          expect(
            (await (newDb.select(
              newDb.familyChildren,
            )..orderBy([(c) => OrderingTerm.asc(c.id)])).get()).map(
              (c) => (c.id, c.familyId, c.personId),
            ),
            [(1, 2, 5), (2, 1, 3)],
          );
          expect(
            (await newDb.select(newDb.events).get()).map((e) => e.toJson()),
            events.map((e) => e.toJson()),
          );
          expect(
            (await newDb.select(newDb.assertions).get()).map(
              (a) => (
                a.id,
                a.eventId,
                a.burialId,
                a.familyId,
                a.familyChildId,
                a.sourceKind,
                a.status,
                a.recordedAt,
              ),
            ),
            claims.map(
              (a) => (
                a.id,
                a.eventId,
                a.burialId,
                null,
                null,
                a.sourceKind,
                a.status,
                a.recordedAt,
              ),
            ),
          );
          expect(
            (await newDb.select(newDb.personMedia).get()).map(
              (l) => l.toJson(),
            ),
            links.map((l) => l.toJson()),
          );
          for (final String table in [
            'persons',
            'families',
            'family_partners',
            'family_children',
            'events',
            'burials',
            'assertions',
            'media',
            'person_media',
          ]) {
            final int count =
                (await newDb
                        .customSelect('SELECT count(*) AS c FROM $table')
                        .getSingle())
                    .read<int>('c');
            final int before = switch (table) {
              'persons' => persons.length,
              'families' => families.length,
              'family_partners' => partners.length,
              'family_children' => children.length,
              'events' => events.length,
              'burials' => burials.length,
              'assertions' => claims.length,
              'media' => media.length,
              _ => links.length,
            };
            expect(count, before, reason: '$table: no row added or lost');
          }
          expect(
            await newDb.customSelect('PRAGMA foreign_key_check').get(),
            isEmpty,
          );
        },
      );
    },
  );

  test(
    'ISSUE-025 AC-4 — v6 to v7 keeps every row and id; every person comes '
    'without a sex, and a family keeps its wedding and end as they were',
    () async {
      const List<v6.PersonsData> persons = [
        v6.PersonsData(
          id: 1,
          givenNames: 'Jan',
          surname: 'Wymyślony',
          bio: 'Kowal.',
          bioSource: 'notatki',
          isLiving: 0,
        ),
        v6.PersonsData(
          id: 2,
          givenNames: 'Maria',
          surname: 'Wymyślona',
          birthSurname: 'Testowa',
          isLiving: 0,
        ),
        v6.PersonsData(
          id: 3,
          givenNames: 'Stanisław',
          surname: 'Wymyślony',
          isLiving: 0,
        ),
      ];
      const List<v6.FamiliesData> families = [v6.FamiliesData(id: 1)];
      const List<v6.FamilyPartnersData> partners = [
        v6.FamilyPartnersData(familyId: 1, personId: 1),
        v6.FamilyPartnersData(familyId: 1, personId: 2),
      ];
      const List<v6.FamilyChildrenData> children = [
        v6.FamilyChildrenData(id: 1, familyId: 1, personId: 3),
      ];
      const List<v6.EventsData> events = [
        v6.EventsData(
          id: 1,
          type: 'marriage',
          familyId: 1,
          qualifier: 'about',
          year: 1948,
        ),
        v6.EventsData(
          id: 2,
          type: 'end',
          familyId: 1,
          qualifier: 'exact',
          year: 1960,
        ),
      ];
      const List<v6.AssertionsData> claims = [
        v6.AssertionsData(
          id: 1,
          eventId: 1,
          sourceKind: 'notes',
          status: 'claimed',
          recordedAt: 1,
        ),
        v6.AssertionsData(
          id: 2,
          eventId: 2,
          sourceKind: 'notes',
          status: 'claimed',
          recordedAt: 2,
        ),
        v6.AssertionsData(
          id: 3,
          familyId: 1,
          sourceKind: 'notes',
          status: 'claimed',
          recordedAt: 3,
        ),
        v6.AssertionsData(
          id: 4,
          familyChildId: 1,
          sourceKind: 'notes',
          status: 'claimed',
          recordedAt: 4,
        ),
      ];

      await verifier.testWithDataIntegrity(
        oldVersion: 6,
        newVersion: 7,
        createOld: v6.DatabaseAtV6.new,
        createNew: v7.DatabaseAtV7.new,
        openTestedDatabase: GrobingDatabase.new,
        createItems: (batch, oldDb) {
          batch.insertAll(oldDb.persons, persons);
          batch.insertAll(oldDb.families, families);
          batch.insertAll(oldDb.familyPartners, partners);
          batch.insertAll(oldDb.familyChildren, children);
          batch.insertAll(oldDb.events, events);
          batch.insertAll(oldDb.assertions, claims);
        },
        validateItems: (newDb) async {
          final List<v7.PersonsData> after = await newDb
              .select(newDb.persons)
              .get();
          expect(
            after.map(
              (p) => (
                p.id,
                p.givenNames,
                p.surname,
                p.birthSurname,
                p.bio,
                p.bioSource,
                p.sex,
              ),
            ),
            persons.map(
              (p) => (
                p.id,
                p.givenNames,
                p.surname,
                p.birthSurname,
                p.bio,
                p.bioSource,
                null,
              ),
            ),
          );
          expect(
            (await newDb.select(newDb.events).get()).map((e) => e.toJson()),
            events.map((e) => e.toJson()),
          );
          expect(
            (await newDb.select(newDb.assertions).get()).map((a) => a.toJson()),
            claims.map((a) => a.toJson()),
          );
          for (final (String table, int before) in [
            ('persons', persons.length),
            ('families', families.length),
            ('family_partners', partners.length),
            ('family_children', children.length),
            ('events', events.length),
            ('assertions', claims.length),
          ]) {
            final int count =
                (await newDb
                        .customSelect('SELECT count(*) AS c FROM $table')
                        .getSingle())
                    .read<int>('c');
            expect(count, before, reason: '$table: no row added or lost');
          }
        },
      );
    },
  );
}
