// dart format width=80
// ignore_for_file: unused_local_variable, unused_import
import 'package:drift/drift.dart';
import 'package:drift_dev/api/migrations_native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:grobing/data/database.dart';
import 'generated/schema.dart';

import 'generated/schema_v1.dart' as v1;
import 'generated/schema_v2.dart' as v2;
import 'generated/schema_v3.dart' as v3;
import 'generated/schema_v4.dart' as v4;
import 'generated/schema_v5.dart' as v5;

// NFR-003: every schema change ships with a migration tested from the previous version. Generated by
// `make-migrations`; the data tests below are ISSUE-011 AC-3 (v1→v2), ISSUE-012 (v2→v3), ISSUE-017
// F2 (v3→v4) and ISSUE-018 F2 (v4→v5). Made-up people only (family-data.md).

void main() {
  driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
  late SchemaVerifier verifier;

  setUpAll(() {
    verifier = SchemaVerifier(GeneratedHelper());
  });

  group('simple database migrations', () {
    // These simple tests verify all possible schema updates with a simple (no
    // data) migration. This is a quick way to ensure that written database
    // migrations properly alter the schema.
    const versions = GeneratedHelper.versions;
    for (final (i, fromVersion) in versions.indexed) {
      group('from $fromVersion', () {
        for (final toVersion in versions.skip(i + 1)) {
          test('to $toVersion', () async {
            final schema = await verifier.schemaAt(fromVersion);
            final db = GrobingDatabase(schema.newConnection());
            await verifier.migrateAndValidate(db, toVersion);
            await db.close();
          });
        }
      });
    }
  });

  test(
    'ISSUE-011 AC-3 — v1 to v2 keeps every row; burials keep their order, '
    'and every date and burial gets one claim carried over from v1 (D5)',
    () async {
      const List<v1.PersonsData> persons = [
        v1.PersonsData(
          id: 1,
          givenNames: 'Ojciec 1',
          surname: 'Wymyślona',
          bio: 'Osoba wymyślona do testów.',
          bioSource: 'dane testowe',
          isLiving: 0,
        ),
        v1.PersonsData(
          id: 2,
          givenNames: 'Matka 1',
          surname: 'Wymyślona',
          birthSurname: 'Zmyślona',
          isLiving: 0,
        ),
        v1.PersonsData(id: 3, givenNames: 'Dziecko 1', isLiving: 1),
      ];
      const List<v1.CemeteriesData> cemeteries = [
        v1.CemeteriesData(id: 1, name: 'Cmentarz Wymyślony 1'),
      ];
      const List<v1.GravesData> graves = [
        v1.GravesData(id: 1, cemeteryId: 1),
        v1.GravesData(id: 2, cemeteryId: 1, sector: 'B', row: '3', plot: '12'),
      ];
      const List<v1.EventsData> events = [
        v1.EventsData(
          id: 1,
          type: 'birth',
          personId: 1,
          qualifier: 'about',
          year: 1890,
        ),
        v1.EventsData(
          id: 2,
          type: 'death',
          personId: 1,
          qualifier: 'exact',
          year: 1951,
          month: 3,
          day: 14,
        ),
        v1.EventsData(
          id: 3,
          type: 'birth',
          personId: 2,
          qualifier: 'between',
          year: 1893,
          yearTo: 1895,
        ),
      ];
      // Not in person order: the new id comes from the row (its rowid), not
      // from the person.
      const List<v1.BurialsData> burials = [
        v1.BurialsData(personId: 3, graveId: 2),
        v1.BurialsData(personId: 1, graveId: 1),
        v1.BurialsData(personId: 2, graveId: 1),
      ];
      final int before = DateTime.now().millisecondsSinceEpoch ~/ 1000;

      await verifier.testWithDataIntegrity(
        oldVersion: 1,
        newVersion: 2,
        createOld: v1.DatabaseAtV1.new,
        createNew: v2.DatabaseAtV2.new,
        openTestedDatabase: GrobingDatabase.new,
        createItems: (batch, oldDb) {
          batch.insertAll(oldDb.persons, persons);
          batch.insertAll(oldDb.cemeteries, cemeteries);
          batch.insertAll(oldDb.graves, graves);
          batch.insertAll(oldDb.events, events);
          batch.insertAll(oldDb.burials, burials);
        },
        validateItems: (newDb) async {
          // Tables v2 does not reshape: the same rows, value for value.
          void same(List<DataClass> now, List<DataClass> then) =>
              expect(now.map((r) => r.toJson()), then.map((r) => r.toJson()));
          same(await newDb.select(newDb.persons).get(), persons);
          same(await newDb.select(newDb.cemeteries).get(), cemeteries);
          same(await newDb.select(newDb.graves).get(), graves);
          same(await newDb.select(newDb.events).get(), events);

          expect(
            (await newDb.select(newDb.burials).get()).map(
              (b) => (b.id, b.personId, b.graveId),
            ),
            [(1, 3, 2), (2, 1, 1), (3, 2, 1)],
          );

          final int after = DateTime.now().millisecondsSinceEpoch ~/ 1000;
          final List<v2.AssertionsData> claims = await newDb
              .select(newDb.assertions)
              .get();
          expect(
            claims.map(
              (c) => (
                c.eventId,
                c.burialId,
                c.sourceKind,
                c.sourceDetail,
                c.status,
              ),
            ),
            [
              for (final int e in [1, 2, 3])
                (e, null, 'notes', carriedOverFromV1, 'claimed'),
              for (final int b in [1, 2, 3])
                (null, b, 'notes', carriedOverFromV1, 'claimed'),
            ],
          );
          expect(
            claims.map((c) => c.recordedAt),
            everyElement(inInclusiveRange(before, after)),
          );
        },
      );
    },
  );

  test(
    'ISSUE-012 — v2 to v3 keeps every row value for value; graves get an empty name',
    () async {
      const List<v2.PersonsData> persons = [
        v2.PersonsData(
          id: 1,
          givenNames: 'Jan',
          surname: 'Wymyślony',
          bio: 'Kowal, wymyślony do testów.',
          bioSource: 'notatki',
          isLiving: 0,
        ),
        v2.PersonsData(
          id: 2,
          givenNames: 'Anna',
          surname: 'Wymyślona',
          birthSurname: 'Zmyślona',
          isLiving: 0,
        ),
      ];
      const List<v2.CemeteriesData> cemeteries = [
        v2.CemeteriesData(
          id: 1,
          name: 'Cmentarz Wymyślony',
          locality: 'Miejscowość Testowa',
          centerLat: 51,
          centerLon: 20,
        ),
      ];
      const List<v2.GravesData> graves = [
        v2.GravesData(id: 1, cemeteryId: 1),
        v2.GravesData(id: 2, cemeteryId: 1, sector: 'B', row: '4', plot: '12'),
      ];
      const List<v2.EventsData> events = [
        v2.EventsData(
          id: 1,
          type: 'birth',
          personId: 1,
          qualifier: 'about',
          year: 1890,
        ),
        v2.EventsData(
          id: 2,
          type: 'birth',
          personId: 2,
          qualifier: 'between',
          year: 1893,
          yearTo: 1895,
        ),
      ];
      const List<v2.BurialsData> burials = [
        v2.BurialsData(id: 1, personId: 1, graveId: 1),
        v2.BurialsData(id: 2, personId: 2, graveId: 1),
      ];
      const List<v2.AssertionsData> claims = [
        v2.AssertionsData(
          id: 1,
          eventId: 1,
          sourceKind: 'notes',
          status: 'claimed',
          recordedAt: 1791273600,
        ),
        v2.AssertionsData(
          id: 2,
          eventId: 2,
          sourceKind: 'grandmother',
          sourceDetail: 'babcia, rozmowa',
          status: 'contradicted',
          recordedAt: 1791273601,
        ),
        v2.AssertionsData(
          id: 3,
          burialId: 1,
          sourceKind: 'notes',
          status: 'claimed',
          recordedAt: 1791273602,
        ),
        v2.AssertionsData(
          id: 4,
          burialId: 2,
          sourceKind: 'notes',
          status: 'claimed',
          recordedAt: 1791273603,
        ),
      ];

      await verifier.testWithDataIntegrity(
        oldVersion: 2,
        newVersion: 3,
        createOld: v2.DatabaseAtV2.new,
        createNew: v3.DatabaseAtV3.new,
        openTestedDatabase: GrobingDatabase.new,
        createItems: (batch, oldDb) {
          batch.insertAll(oldDb.persons, persons);
          batch.insertAll(oldDb.cemeteries, cemeteries);
          batch.insertAll(oldDb.graves, graves);
          batch.insertAll(oldDb.events, events);
          batch.insertAll(oldDb.burials, burials);
          batch.insertAll(oldDb.assertions, claims);
        },
        validateItems: (newDb) async {
          void same(List<DataClass> now, List<DataClass> then) =>
              expect(now.map((r) => r.toJson()), then.map((r) => r.toJson()));
          same(await newDb.select(newDb.persons).get(), persons);
          same(await newDb.select(newDb.cemeteries).get(), cemeteries);
          same(await newDb.select(newDb.events).get(), events);
          same(await newDb.select(newDb.burials).get(), burials);
          same(await newDb.select(newDb.assertions).get(), claims);

          // Graves: the same values, and the new name empty — never derived from the people.
          final List<v3.GravesData> migrated = await newDb
              .select(newDb.graves)
              .get();
          expect(migrated.map((g) => g.name), everyElement(equals(null)));
          expect(
            migrated.map((g) => g.toJson()..remove('name')),
            graves.map((g) => g.toJson()),
          );
        },
      );
    },
  );

  test(
    'ISSUE-017 F2 — v3 to v4 keeps every row; each person photo becomes a link of that person in the order '
    'of its id (the first stays the profile), the grave keeps its photo, no reference breaks',
    () async {
      const List<v3.PersonsData> persons = [
        v3.PersonsData(
          id: 1,
          givenNames: 'Jan',
          surname: 'Wymyślony',
          isLiving: 0,
        ),
        v3.PersonsData(
          id: 2,
          givenNames: 'Anna',
          surname: 'Wymyślona',
          isLiving: 0,
        ),
        v3.PersonsData(
          id: 3,
          givenNames: 'Józef',
          surname: 'Wymyślony',
          isLiving: 0,
        ),
      ];
      const List<v3.CemeteriesData> cemeteries = [
        v3.CemeteriesData(id: 1, name: 'Cmentarz Wymyślony'),
      ];
      const List<v3.GravesData> graves = [
        v3.GravesData(id: 1, cemeteryId: 1, name: 'Grób Wymyślonych'),
      ];
      // Interleaved ids: Anna's photos are 2 and 5, so her order comes from the id, not the insert batch.
      const List<v3.MediaData> media = [
        v3.MediaData(id: 1, relativePath: 'groby/1/nagrobek.jpg', graveId: 1),
        v3.MediaData(id: 2, relativePath: 'osoby/anna-a.jpg', personId: 2),
        v3.MediaData(id: 3, relativePath: 'osoby/jan-a.jpg', personId: 1),
        v3.MediaData(id: 5, relativePath: 'osoby/anna-b.jpg', personId: 2),
      ];

      await verifier.testWithDataIntegrity(
        oldVersion: 3,
        newVersion: 4,
        createOld: v3.DatabaseAtV3.new,
        createNew: v4.DatabaseAtV4.new,
        openTestedDatabase: GrobingDatabase.new,
        createItems: (batch, oldDb) {
          batch.insertAll(oldDb.persons, persons);
          batch.insertAll(oldDb.cemeteries, cemeteries);
          batch.insertAll(oldDb.graves, graves);
          batch.insertAll(oldDb.media, media);
        },
        validateItems: (newDb) async {
          expect(
            (await newDb.select(newDb.persons).get()).map((p) => p.toJson()),
            persons.map((p) => p.toJson()),
          );
          // Every media row and id stays (a v3 restore counts them), without person_id now.
          expect(
            (await newDb.select(newDb.media).get()).map(
              (m) => (m.id, m.relativePath, m.graveId),
            ),
            media.map((m) => (m.id, m.relativePath, m.graveId)),
          );
          final List<v4.PersonMediaData> links =
              await (newDb.select(newDb.personMedia)..orderBy([
                    (l) => OrderingTerm.asc(l.personId),
                    (l) => OrderingTerm.asc(l.position),
                  ]))
                  .get();
          expect(links.map((l) => (l.personId, l.mediaId, l.position)), [
            (1, 3, 0),
            (2, 2, 0),
            (2, 5, 1),
          ]);
          // Józef had no photo and has no link; the grave's photo has none either.
          expect(
            links.where((l) => l.personId == 3 || l.mediaId == 1),
            isEmpty,
          );
          expect(
            await newDb.customSelect('PRAGMA foreign_key_check').get(),
            isEmpty,
          );
        },
      );
    },
  );

  test(
    'ISSUE-018 F2 — v4 to v5 keeps every row, link and position; every link has no crop, so every profile '
    'circle shows the middle as before; no reference breaks',
    () async {
      const List<v4.PersonsData> persons = [
        v4.PersonsData(
          id: 1,
          givenNames: 'Jan',
          surname: 'Wymyślony',
          isLiving: 0,
        ),
        v4.PersonsData(
          id: 2,
          givenNames: 'Anna',
          surname: 'Wymyślona',
          isLiving: 0,
        ),
      ];
      const List<v4.CemeteriesData> cemeteries = [
        v4.CemeteriesData(id: 1, name: 'Cmentarz Wymyślony'),
      ];
      const List<v4.GravesData> graves = [
        v4.GravesData(id: 1, cemeteryId: 1, name: 'Grób Wymyślonych'),
      ];
      // A gravestone, a photo shared by both (Jan's profile, Anna's second) and Anna's own profile.
      const List<v4.MediaData> media = [
        v4.MediaData(id: 1, relativePath: 'groby/1/nagrobek.jpg', graveId: 1),
        v4.MediaData(id: 2, relativePath: 'zdjecia/slub.jpg'),
        v4.MediaData(id: 3, relativePath: 'zdjecia/anna.jpg'),
      ];
      const List<v4.PersonMediaData> links = [
        v4.PersonMediaData(personId: 1, mediaId: 2, position: 0),
        v4.PersonMediaData(personId: 2, mediaId: 3, position: 0),
        v4.PersonMediaData(personId: 2, mediaId: 2, position: 1),
      ];

      await verifier.testWithDataIntegrity(
        oldVersion: 4,
        newVersion: 5,
        createOld: v4.DatabaseAtV4.new,
        createNew: v5.DatabaseAtV5.new,
        openTestedDatabase: GrobingDatabase.new,
        createItems: (batch, oldDb) {
          batch.insertAll(oldDb.persons, persons);
          batch.insertAll(oldDb.cemeteries, cemeteries);
          batch.insertAll(oldDb.graves, graves);
          batch.insertAll(oldDb.media, media);
          batch.insertAll(oldDb.personMedia, links);
        },
        validateItems: (newDb) async {
          expect(
            (await newDb.select(newDb.persons).get()).map((p) => p.toJson()),
            persons.map((p) => p.toJson()),
          );
          expect(
            (await newDb.select(newDb.media).get()).map(
              (m) => (m.id, m.relativePath, m.graveId),
            ),
            media.map((m) => (m.id, m.relativePath, m.graveId)),
          );
          final List<v5.PersonMediaData> after =
              await (newDb.select(newDb.personMedia)..orderBy([
                    (l) => OrderingTerm.asc(l.personId),
                    (l) => OrderingTerm.asc(l.position),
                  ]))
                  .get();
          expect(
            after.map(
              (l) => (
                l.personId,
                l.mediaId,
                l.position,
                l.cropLeft,
                l.cropTop,
                l.cropWidth,
                l.cropHeight,
              ),
            ),
            [
              (1, 2, 0, null, null, null, null),
              (2, 3, 0, null, null, null, null),
              (2, 2, 1, null, null, null, null),
            ],
          );
          expect(
            await newDb.customSelect('PRAGMA foreign_key_check').get(),
            isEmpty,
          );
        },
      );
    },
  );
}
